/*
 Navicat Premium Data Transfer

 Source Server         : trial
 Source Server Type    : MySQL
 Source Server Version : 80031 (8.0.31)
 Source Host           : localhost:3306
 Source Schema         : test

 Target Server Type    : MySQL
 Target Server Version : 80031 (8.0.31)
 File Encoding         : 65001

 Date: 12/12/2022 19:10:34
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for pic
-- ----------------------------
DROP TABLE IF EXISTS `pic`;
CREATE TABLE `pic`  (
  `教室名称` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `全景图链接` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`教室名称`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of pic
-- ----------------------------
INSERT INTO `pic` VALUES ('sy-100', 'https://etc.sjtu.edu.cn/vr/s/100/index.html');
INSERT INTO `pic` VALUES ('sy-101', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-102', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-103', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-104', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-105', 'https://etc.sjtu.edu.cn/vr/s/105/index.html');
INSERT INTO `pic` VALUES ('sy-107', 'https://etc.sjtu.edu.cn/vr/s/107/index.html');
INSERT INTO `pic` VALUES ('sy-108', 'https://etc.sjtu.edu.cn/vr/s/107/index.html');
INSERT INTO `pic` VALUES ('sy-110', 'https://etc.sjtu.edu.cn/vr/s/105/index.html');
INSERT INTO `pic` VALUES ('sy-111', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-112', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-115', 'https://etc.sjtu.edu.cn/vr/s/115/index.html');
INSERT INTO `pic` VALUES ('sy-201', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-202', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-203', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-204', 'https://etc.sjtu.edu.cn/vr/s/101/index.html');
INSERT INTO `pic` VALUES ('sy-205', 'https://etc.sjtu.edu.cn/vr/s/105/index.html');
INSERT INTO `pic` VALUES ('sy-207', 'https://etc.sjtu.edu.cn/vr/s/107/index.html');
INSERT INTO `pic` VALUES ('sy-210', 'https://etc.sjtu.edu.cn/vr/s/105/index.html');
INSERT INTO `pic` VALUES ('sy-211', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-212', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-213', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-215', 'https://etc.sjtu.edu.cn/vr/s/115/index.html');
INSERT INTO `pic` VALUES ('sy-301', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-302', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-303', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-304', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-305', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-306', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-307', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-308', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-309', 'https://etc.sjtu.edu.cn/vr/s/314/index.html');
INSERT INTO `pic` VALUES ('sy-310', 'https://etc.sjtu.edu.cn/vr/s/313/index.html');
INSERT INTO `pic` VALUES ('sy-311', 'https://etc.sjtu.edu.cn/vr/s/314/index.html');
INSERT INTO `pic` VALUES ('sy-312', 'https://etc.sjtu.edu.cn/vr/s/314/index.html');
INSERT INTO `pic` VALUES ('sy-313', 'https://etc.sjtu.edu.cn/vr/s/313/index.html');
INSERT INTO `pic` VALUES ('sy-314', 'https://etc.sjtu.edu.cn/vr/s/314/index.html');
INSERT INTO `pic` VALUES ('sy-315', 'https://etc.sjtu.edu.cn/vr/s/115/index.html');
INSERT INTO `pic` VALUES ('sy-317', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-318', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-319', 'https://etc.sjtu.edu.cn/vr/s/111/index.html');
INSERT INTO `pic` VALUES ('sy-405', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-407', 'https://etc.sjtu.edu.cn/vr/s/301/index.html');
INSERT INTO `pic` VALUES ('sy-408', 'https://etc.sjtu.edu.cn/vr/s/408/index.html');
INSERT INTO `pic` VALUES ('sy-409', 'https://etc.sjtu.edu.cn/vr/s/313/index.html');
INSERT INTO `pic` VALUES ('sy-410', 'https://etc.sjtu.edu.cn/vr/s/314/index.html');
INSERT INTO `pic` VALUES ('sy-515', 'https://etc.sjtu.edu.cn/vr/s/515/index.html');
INSERT INTO `pic` VALUES ('zy-101', 'https://etc.sjtu.edu.cn/vr/z/101/index.html');
INSERT INTO `pic` VALUES ('zy-102', 'https://etc.sjtu.edu.cn/vr/z/102/index.html');
INSERT INTO `pic` VALUES ('zy-103', 'https://etc.sjtu.edu.cn/vr/z/103/index.html');
INSERT INTO `pic` VALUES ('zy-104', 'https://etc.sjtu.edu.cn/vr/z/102/index.html');
INSERT INTO `pic` VALUES ('zy-105', 'https://etc.sjtu.edu.cn/vr/z/105/index.html');
INSERT INTO `pic` VALUES ('zy-106', 'https://etc.sjtu.edu.cn/vr/z/105/index.html');
INSERT INTO `pic` VALUES ('zy-107', 'https://etc.sjtu.edu.cn/vr/z/105/index.html');
INSERT INTO `pic` VALUES ('zy-111', 'https://etc.sjtu.edu.cn/vr/z/111/index.html');
INSERT INTO `pic` VALUES ('zy-112', 'https://etc.sjtu.edu.cn/vr/z/112/index.html');
INSERT INTO `pic` VALUES ('zy-113', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-114', 'https://etc.sjtu.edu.cn/vr/z/114/index.html');
INSERT INTO `pic` VALUES ('zy-115', 'https://etc.sjtu.edu.cn/vr/z/114/index.html');
INSERT INTO `pic` VALUES ('zy-201', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-202', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-203', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-204', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-205', 'https://etc.sjtu.edu.cn/vr/z/205/index.html');
INSERT INTO `pic` VALUES ('zy-206', 'https://etc.sjtu.edu.cn/vr/z/205/index.html');
INSERT INTO `pic` VALUES ('zy-207', 'https://etc.sjtu.edu.cn/vr/z/207/index.html');
INSERT INTO `pic` VALUES ('zy-211', 'https://etc.sjtu.edu.cn/vr/z/211/index.html');
INSERT INTO `pic` VALUES ('zy-212', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-213', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-301', 'https://etc.sjtu.edu.cn/vr/z/301/index.html');
INSERT INTO `pic` VALUES ('zy-302', 'https://etc.sjtu.edu.cn/vr/z/301/index.html');
INSERT INTO `pic` VALUES ('zy-303', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-304', 'https://etc.sjtu.edu.cn/vr/z/201/index.html');
INSERT INTO `pic` VALUES ('zy-305', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-306', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-307', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-310', 'https://etc.sjtu.edu.cn/vr/z/310/index.html');
INSERT INTO `pic` VALUES ('zy-311', 'https://etc.sjtu.edu.cn/vr/z/211/index.html');
INSERT INTO `pic` VALUES ('zy-312', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-313', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-401', 'https://etc.sjtu.edu.cn/vr/z/401/index.html');
INSERT INTO `pic` VALUES ('zy-402', 'https://etc.sjtu.edu.cn/vr/z/403/index.html');
INSERT INTO `pic` VALUES ('zy-403', 'https://etc.sjtu.edu.cn/vr/z/403/index.html');
INSERT INTO `pic` VALUES ('zy-404', 'https://etc.sjtu.edu.cn/vr/z/403/index.html');
INSERT INTO `pic` VALUES ('zy-405', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-406', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-407', 'https://etc.sjtu.edu.cn/vr/z/305/index.html');
INSERT INTO `pic` VALUES ('zy-411', 'https://etc.sjtu.edu.cn/vr/z/211/index.html');
INSERT INTO `pic` VALUES ('zy-412', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-413', 'https://etc.sjtu.edu.cn/vr/z/113/index.html');
INSERT INTO `pic` VALUES ('zy-505', 'https://etc.sjtu.edu.cn/vr/z/505/index.html');
INSERT INTO `pic` VALUES ('zy-506', 'https://etc.sjtu.edu.cn/vr/z/506/index.html');
INSERT INTO `pic` VALUES ('zy-507', 'https://etc.sjtu.edu.cn/vr/z/507/index.html');
INSERT INTO `pic` VALUES ('zy-508', 'https://etc.sjtu.edu.cn/vr/z/508/index.html');
INSERT INTO `pic` VALUES ('zy-510', 'https://etc.sjtu.edu.cn/vr/z/510/index.html');
INSERT INTO `pic` VALUES ('下院 101', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 102', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 103', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 104', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 105', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 106', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 107', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 111', 'https://etc.sjtu.edu.cn/vr/x/411/index.html');
INSERT INTO `pic` VALUES ('下院 112', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 113', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 114', 'https://etc.sjtu.edu.cn/vr/x/114/index.html');
INSERT INTO `pic` VALUES ('下院 115', 'https://etc.sjtu.edu.cn/vr/x/114/index.html');
INSERT INTO `pic` VALUES ('下院 201', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 202', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 203', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 204', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 205', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 206', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 207', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 209', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 211', 'https://etc.sjtu.edu.cn/vr/x/411/index.html');
INSERT INTO `pic` VALUES ('下院 212', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 213', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 301', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 302', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 303', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 304', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 305', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 306', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 307', 'https://etc.sjtu.edu.cn/vr/x/206/index.html');
INSERT INTO `pic` VALUES ('下院 310', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 311', 'https://etc.sjtu.edu.cn/vr/x/411/index.html');
INSERT INTO `pic` VALUES ('下院 312', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 313', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 401', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 402', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 403', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 404', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 408', 'https://etc.sjtu.edu.cn/vr/x/408/index.html');
INSERT INTO `pic` VALUES ('下院 410', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('下院 411', 'https://etc.sjtu.edu.cn/vr/x/411/index.html');
INSERT INTO `pic` VALUES ('下院 412', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 413', 'https://etc.sjtu.edu.cn/vr/x/413/index.html');
INSERT INTO `pic` VALUES ('下院 508', 'https://etc.sjtu.edu.cn/vr/x/408/index.html');
INSERT INTO `pic` VALUES ('下院 509', 'https://etc.sjtu.edu.cn/vr/x/209/index.html');
INSERT INTO `pic` VALUES ('东上院 100', 'https://etc.sjtu.edu.cn/vr/dsy/100/index.html');
INSERT INTO `pic` VALUES ('东上院 101', 'https://etc.sjtu.edu.cn/vr/dsy/101/index.html');
INSERT INTO `pic` VALUES ('东上院 102', 'https://etc.sjtu.edu.cn/vr/dsy/102/index.html');
INSERT INTO `pic` VALUES ('东上院 105', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 106', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 107', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 111', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 112', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 115', 'https://etc.sjtu.edu.cn/vr/dsy/115/index.html');
INSERT INTO `pic` VALUES ('东上院 201', 'https://etc.sjtu.edu.cn/vr/dsy/101/index.html');
INSERT INTO `pic` VALUES ('东上院 202', 'https://etc.sjtu.edu.cn/vr/dsy/102/index.html');
INSERT INTO `pic` VALUES ('东上院 205', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 206', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 207', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 211', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 212', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 215', 'https://etc.sjtu.edu.cn/vr/dsy/115/index.html');
INSERT INTO `pic` VALUES ('东上院 301', 'https://etc.sjtu.edu.cn/vr/dsy/301/index.html');
INSERT INTO `pic` VALUES ('东上院 302', 'https://etc.sjtu.edu.cn/vr/dsy/301/index.html');
INSERT INTO `pic` VALUES ('东上院 303', 'https://etc.sjtu.edu.cn/vr/dsy/301/index.html');
INSERT INTO `pic` VALUES ('东上院 304', 'https://etc.sjtu.edu.cn/vr/dsy/301/index.html');
INSERT INTO `pic` VALUES ('东上院 307', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 308', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 309', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 311', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 312', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 315', 'https://etc.sjtu.edu.cn/vr/dsy/115/index.html');
INSERT INTO `pic` VALUES ('东上院 407', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 408', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 409', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 411', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 412', 'https://etc.sjtu.edu.cn/vr/dsy/111/index.html');
INSERT INTO `pic` VALUES ('东上院 415', 'https://etc.sjtu.edu.cn/vr/dsy/115/index.html');
INSERT INTO `pic` VALUES ('东上院 501', 'https://etc.sjtu.edu.cn/vr/dsy/501/index.html');
INSERT INTO `pic` VALUES ('东上院 502', 'https://etc.sjtu.edu.cn/vr/dsy/501/index.html');
INSERT INTO `pic` VALUES ('东上院 503', 'https://etc.sjtu.edu.cn/vr/dsy/501/index.html');
INSERT INTO `pic` VALUES ('东上院 504', 'https://etc.sjtu.edu.cn/vr/dsy/501/index.html');
INSERT INTO `pic` VALUES ('东上院 507', 'https://etc.sjtu.edu.cn/vr/dsy/501/index.html');
INSERT INTO `pic` VALUES ('东上院 508', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东上院 509', 'https://etc.sjtu.edu.cn/vr/dsy/105/index.html');
INSERT INTO `pic` VALUES ('东下院 102', 'https://etc.sjtu.edu.cn/vr/dxy/202/index.html');
INSERT INTO `pic` VALUES ('东下院 103', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 104', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 105', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 111', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 112', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 113', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 115', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 202', 'https://etc.sjtu.edu.cn/vr/dxy/202/index.html');
INSERT INTO `pic` VALUES ('东下院 203', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 204', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 205', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 206', 'https://etc.sjtu.edu.cn/vr/dxy/307/index.html');
INSERT INTO `pic` VALUES ('东下院 209', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 211', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 212', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 213', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 215', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 302', 'https://etc.sjtu.edu.cn/vr/dxy/202/index.html');
INSERT INTO `pic` VALUES ('东下院 303', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 304', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 305', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 307', 'https://etc.sjtu.edu.cn/vr/dxy/307/index.html');
INSERT INTO `pic` VALUES ('东下院 308', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 309', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 310', 'https://etc.sjtu.edu.cn/vr/dxy/307/index.html');
INSERT INTO `pic` VALUES ('东下院 311', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 312', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 313', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 315', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 402', 'https://etc.sjtu.edu.cn/vr/dxy/402/index.html');
INSERT INTO `pic` VALUES ('东下院 403', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 404', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 405', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 406', 'https://etc.sjtu.edu.cn/vr/dxy/307/index.html');
INSERT INTO `pic` VALUES ('东下院 407', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 408', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 409', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 415', 'https://etc.sjtu.edu.cn/vr/dxy/415/index.html');
INSERT INTO `pic` VALUES ('东下院 502', 'https://etc.sjtu.edu.cn/vr/dxy/402/index.html');
INSERT INTO `pic` VALUES ('东下院 503', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东下院 504', 'https://etc.sjtu.edu.cn/vr/dxy/204/index.html');
INSERT INTO `pic` VALUES ('东中院 1-105', 'https://etc.sjtu.edu.cn/vr/dzy/1-105/index.html');
INSERT INTO `pic` VALUES ('东中院 1-106', 'https://etc.sjtu.edu.cn/vr/dzy/1-106/index.html');
INSERT INTO `pic` VALUES ('东中院 1-107', 'https://etc.sjtu.edu.cn/vr/dzy/1-107/index.html');
INSERT INTO `pic` VALUES ('东中院 1-108', 'https://etc.sjtu.edu.cn/vr/dzy/1-108/index.html');
INSERT INTO `pic` VALUES ('东中院 1-109', 'https://etc.sjtu.edu.cn/vr/dzy/1-109/index.html');
INSERT INTO `pic` VALUES ('东中院 1-201', 'https://etc.sjtu.edu.cn/vr/dzy/1-201/index.html');
INSERT INTO `pic` VALUES ('东中院 1-202', 'https://etc.sjtu.edu.cn/vr/dzy/1-201/index.html');
INSERT INTO `pic` VALUES ('东中院 1-203', 'https://etc.sjtu.edu.cn/vr/dzy/1-203/index.html');
INSERT INTO `pic` VALUES ('东中院 1-204', 'https://etc.sjtu.edu.cn/vr/dzy/1-203/index.html');
INSERT INTO `pic` VALUES ('东中院 1-301', 'https://etc.sjtu.edu.cn/vr/dzy/1-201/index.html');
INSERT INTO `pic` VALUES ('东中院 1-302', 'https://etc.sjtu.edu.cn/vr/dzy/1-201/index.html');
INSERT INTO `pic` VALUES ('东中院 1-303', 'https://etc.sjtu.edu.cn/vr/dzy/1-203/index.html');
INSERT INTO `pic` VALUES ('东中院 1-304', 'https://etc.sjtu.edu.cn/vr/dzy/1-203/index.html');
INSERT INTO `pic` VALUES ('东中院 2-101', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-102', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-103', 'https://etc.sjtu.edu.cn/vr/dzy/2-103/index.html');
INSERT INTO `pic` VALUES ('东中院 2-106', 'https://etc.sjtu.edu.cn/vr/dzy/2-106/index.html');
INSERT INTO `pic` VALUES ('东中院 2-201', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-202', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-203', 'https://etc.sjtu.edu.cn/vr/dzy/2-103/index.html');
INSERT INTO `pic` VALUES ('东中院 2-206', 'https://etc.sjtu.edu.cn/vr/dzy/2-106/index.html');
INSERT INTO `pic` VALUES ('东中院 2-301', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-302', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-303', 'https://etc.sjtu.edu.cn/vr/dzy/2-103/index.html');
INSERT INTO `pic` VALUES ('东中院 2-305', 'https://etc.sjtu.edu.cn/vr/dzy/2-305/index.html');
INSERT INTO `pic` VALUES ('东中院 2-306', 'https://etc.sjtu.edu.cn/vr/dzy/2-106/index.html');
INSERT INTO `pic` VALUES ('东中院 2-401', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-402', 'https://etc.sjtu.edu.cn/vr/dzy/2-101/index.html');
INSERT INTO `pic` VALUES ('东中院 2-403', 'https://etc.sjtu.edu.cn/vr/dzy/2-103/index.html');
INSERT INTO `pic` VALUES ('东中院 2-405', 'https://etc.sjtu.edu.cn/vr/dzy/2-305/index.html');
INSERT INTO `pic` VALUES ('东中院 2-406', 'https://etc.sjtu.edu.cn/vr/dzy/2-305/index.html');
INSERT INTO `pic` VALUES ('东中院 3-102', 'https://etc.sjtu.edu.cn/vr/dzy/3-102/index.html');
INSERT INTO `pic` VALUES ('东中院 3-104', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-105', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-106', 'https://etc.sjtu.edu.cn/vr/dzy/3-106/index.html');
INSERT INTO `pic` VALUES ('东中院 3-202', 'https://etc.sjtu.edu.cn/vr/dzy/3-102/index.html');
INSERT INTO `pic` VALUES ('东中院 3-204', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-205', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-206', 'https://etc.sjtu.edu.cn/vr/dzy/3-106/index.html');
INSERT INTO `pic` VALUES ('东中院 3-302', 'https://etc.sjtu.edu.cn/vr/dzy/3-102/index.html');
INSERT INTO `pic` VALUES ('东中院 3-304', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-305', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-306', 'https://etc.sjtu.edu.cn/vr/dzy/3-106/index.html');
INSERT INTO `pic` VALUES ('东中院 3-402', 'https://etc.sjtu.edu.cn/vr/dzy/3-102/index.html');
INSERT INTO `pic` VALUES ('东中院 3-404', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-405', 'https://etc.sjtu.edu.cn/vr/dzy/3-104/index.html');
INSERT INTO `pic` VALUES ('东中院 3-406', 'https://etc.sjtu.edu.cn/vr/dzy/3-106/index.html');
INSERT INTO `pic` VALUES ('东中院 4-101', 'https://etc.sjtu.edu.cn/vr/dzy/4-101/index.html');
INSERT INTO `pic` VALUES ('东中院 4-102', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-103', 'https://etc.sjtu.edu.cn/vr/dzy/4-103/index.html');
INSERT INTO `pic` VALUES ('东中院 4-104', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-106', 'https://etc.sjtu.edu.cn/vr/dzy/4-106/index.html');
INSERT INTO `pic` VALUES ('东中院 4-201', 'https://etc.sjtu.edu.cn/vr/dzy/4-101/index.html');
INSERT INTO `pic` VALUES ('东中院 4-202', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-203', 'https://etc.sjtu.edu.cn/vr/dzy/4-103/index.html');
INSERT INTO `pic` VALUES ('东中院 4-204', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-206', 'https://etc.sjtu.edu.cn/vr/dzy/4-106/index.html');
INSERT INTO `pic` VALUES ('东中院 4-301', 'https://etc.sjtu.edu.cn/vr/dzy/4-101/index.html');
INSERT INTO `pic` VALUES ('东中院 4-302', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-303', 'https://etc.sjtu.edu.cn/vr/dzy/4-103/index.html');
INSERT INTO `pic` VALUES ('东中院 4-304', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-306', 'https://etc.sjtu.edu.cn/vr/dzy/4-106/index.html');
INSERT INTO `pic` VALUES ('东中院 4-401', 'https://etc.sjtu.edu.cn/vr/dzy/4-101/index.html');
INSERT INTO `pic` VALUES ('东中院 4-402', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-403', 'https://etc.sjtu.edu.cn/vr/dzy/4-103/index.html');
INSERT INTO `pic` VALUES ('东中院 4-404', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-406', 'https://etc.sjtu.edu.cn/vr/dzy/4-106/index.html');
INSERT INTO `pic` VALUES ('东中院 4-501', 'https://etc.sjtu.edu.cn/vr/dzy/4-101/index.html');
INSERT INTO `pic` VALUES ('东中院 4-502', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-503', 'https://etc.sjtu.edu.cn/vr/dzy/4-103/index.html');
INSERT INTO `pic` VALUES ('东中院 4-504', 'https://etc.sjtu.edu.cn/vr/dzy/4-102/index.html');
INSERT INTO `pic` VALUES ('东中院 4-506', 'https://etc.sjtu.edu.cn/vr/dzy/4-106/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 100', 'https://etc.sjtu.edu.cn/vr/crq/100/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 102', 'https://etc.sjtu.edu.cn/vr/crq/102b/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 103', 'https://etc.sjtu.edu.cn/vr/crq/102b/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 104', 'https://etc.sjtu.edu.cn/vr/crq/102b/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 105', 'https://etc.sjtu.edu.cn/vr/crq/102b/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 106', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 107', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 108', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 109', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 110', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 111', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 112', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 113', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 114', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 117', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 121', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 202', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 203', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 204', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 205', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 206', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 207', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 208', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 209', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 210', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 211', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 212', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 213', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 214', 'https://etc.sjtu.edu.cn/vr/crq/214/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 216', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 219', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 223', 'https://etc.sjtu.edu.cn/vr/crq/114/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 302', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 303', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 304', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 305', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 306', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 307', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 308', 'https://etc.sjtu.edu.cn/vr/crq/308/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 309', 'https://etc.sjtu.edu.cn/vr/crq/309/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 310', 'https://etc.sjtu.edu.cn/vr/crq/102/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 311', 'https://etc.sjtu.edu.cn/vr/crq/309/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 312', 'https://etc.sjtu.edu.cn/vr/crq/309/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 402', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 403', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 404', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 405', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 406', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 407', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 408', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 409', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 410', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 411', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 412', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 413', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 414', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 415', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 416', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 417', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 418', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 419', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 420', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 421', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 422', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 423', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 424', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 425', 'https://etc.sjtu.edu.cn/vr/crq/402/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 429', 'https://etc.sjtu.edu.cn/vr/crq/429/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 430', 'https://etc.sjtu.edu.cn/vr/crq/429/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 432', 'https://etc.sjtu.edu.cn/vr/crq/429/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 504', 'https://etc.sjtu.edu.cn/vr/crq/504/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 505', 'https://etc.sjtu.edu.cn/vr/crq/504/index.html');
INSERT INTO `pic` VALUES ('陈瑞球楼 507', 'https://etc.sjtu.edu.cn/vr/crq/429/index.html');

SET FOREIGN_KEY_CHECKS = 1;
